import type { Metadata } from "next";
import { Inter, Poppins, Nunito, Josefin_Sans } from "next/font/google";
import "./globals.css";
import "@/styles/styles.scss";
import Header from "@/components/Header/Header";
const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "400", "500", "600", "800"],
  variable: "--font-poppins",
});
const nunito = Nunito({
  subsets: ["latin"],
  weight: ["200", "400", "500", "600", "800"],
  variable: "--font-nunito",
});
const josefin = Josefin_Sans({
  subsets: ["latin"],
  weight: ["200", "400", "500", "600", "700"],
  variable: "--font-josefin",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${poppins.variable} ${nunito.variable} ${josefin.variable}`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
